In [34]:
from sklearn import svm
import numpy as np
print("Done")

Done


In [31]:
## binary class classification
X = [[0,0],[1,1]]
y = [0,1]
clf = svm.SVC()
print(type(clf))
clf = clf.fit(X,y)
#print(clf)

<class 'sklearn.svm.classes.SVC'>


In [16]:
print(clf.predict([[2,2],[1,2],[0,0]]))

[1 1 0]


In [17]:
print(clf.support_vectors_)
print(clf.support_)


[[ 0.  0.]
 [ 1.  1.]]
[0 1]


In [24]:
## multi class classification
X = [[0],[1],[2],[3]]
y = [0,1,2,3]
clf = svm.SVC(decision_function_shape = 'ovo')
clf.fit(X,y)
#print(clf)
dec = clf.decision_function([[1]])
#print(type(dec))
print(dec)
print(dec.shape)

[[ 1.9370957   3.5         0.9370957  -0.37419139]]
(1, 4)


In [25]:
lin_clf = svm.LinearSVC()
lin_clf = lin_clf.fit(X,y)
dec_l = lin_clf.decision_function([[1]])
print(dec_l.shape)

(1, 4)


In [27]:
## regression
X = [[0,0],[2,2]]
y = [0.5,2.5]
clf_r = svm.SVR()
clf_r = clf_r.fit(X,y)
print(clf_r.predict([[1,1]]))

[ 1.5]


In [32]:
## defining own kernel function4
## i.e. python function as kernel function
def my_kernel(X,Y):
    return np.dot(X,Y.T)
clf_custom = svm.SVC(kernel=my_kernel)
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
## using gram matrix 
clf_pre = svm.SVC(kernel='precomputed')
gram = np.dot(np.array(X),np.array(X).T)
clf_pre.fit(gram,y)

clf_pre.predict(gram)

array([0, 1])