In [2]:
import numpy as np
import time
import sys

print("Done")

Done


In [3]:
## creating numpy array
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
## accessing elements of numpy array
for i in range(0,len(arr)):
    print(arr[i])

1
2
3


In [5]:
## comparing the memory used

p_l = range(1000)
print(sys.getsizeof(p_l[0])*len(p_l))

np_l = np.arange(1000)
print(np_l.size*np_l.itemsize)


24000
4000


In [6]:
## comparing the time required to process

SIZE = 1000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# processing the python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python took : ", time.time()-start)


#processing the numpy arr
start = time.time()
result = a1+a2
print
 





python took :  0.017086505889892578


<function print>

In [7]:
## performing different operations
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a2/a1)


[5 7 9]
[3 3 3]
[ 4 10 18]
[ 4.   2.5  2. ]


In [11]:
## different fields
print(a1.ndim)
print(a1.itemsize)
print(a1.dtype)

arr = np.array([[1,2],[3,4]])
print(arr.shape)

1
4
int32
(2, 2)


In [14]:
## creating np array with zeros and ones
zeros = np.zeros((4,5))
ones = np.ones((4,5))
print(zeros)
print(ones)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [18]:
## python range and numpy arange
print(range(1,7))
print(np.arange(1,8))

print(range(1,10,2))
print(np.arange(1,10,2))

print(np.linspace(1,5,10))

range(1, 7)
[1 2 3 4 5 6 7]
range(1, 10, 2)
[1 3 5 7 9]
[ 1.          1.44444444  1.88888889  2.33333333  2.77777778  3.22222222
  3.66666667  4.11111111  4.55555556  5.        ]


In [25]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.reshape((2,3)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [23]:
print(a.ravel())

[1 2 3 4 5 6]


In [24]:
print(a.min())
print(a.max())
print(a.sum())
print(np.sqrt(a))
print(np.std(a))


1
6
21
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]
 [ 2.23606798  2.44948974]]
1.70782512766


In [27]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[ 9 12]
[ 3  7 11]


In [29]:
print(a.dot(a.T))

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


In [51]:
## indexing slicing
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0:2])
print(a[-1])
print(a[1,2])
print(a[0:2,2])
print(a[0:2,:])
print(a[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[7 8 9]
6
[3 6]
[[1 2 3]
 [4 5 6]]
[2 5 8]


In [38]:
## iterating the array
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [39]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [41]:
## horizontal and vertical stacking 
a = np.arange(6).reshape((3,2))
b = np.arange(6,12).reshape((3,2))
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [48]:
## horizontal and vertical splits
ah = np.arange(30).reshape((2,15))
result = [x for x in np.hsplit(ah,3)]
#print(result)
print(np.vsplit(ah,2))


[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [53]:
## indexing with the boolean array
b = a > 4
print(b)
print(a[b])
a[b] = -1
print(a)

[[False False False]
 [False  True  True]
 [ True  True  True]]
[5 6 7 8 9]
[[ 1  2  3]
 [ 4 -1 -1]
 [-1 -1 -1]]
