In [17]:
import numpy as np
import time
print("Done")

Done


In [3]:
a = np.array([1,2])
b = np.array([2,1])


In [4]:
## performing dot product
dot = 0
for e,f in zip(a,b):
    dot+=e*f
print(dot)

4


In [10]:
## np dot operation
print(a*b)
print(np.sum(a*b))
print((a*b).sum()) # Same as above
print(np.dot(a,b)) # Direct function to do dot product of vector
print(a.dot(b))

[2 2]
4
4
4
4


In [13]:
## calculate the amplitude of vector
amp_a = np.sqrt((a*a).sum())
print(amp_a)
print(np.linalg.norm(a)) # For finding amplitude


2.2360679775
2.2360679775


In [16]:
## calculating the angle
cos_theta = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
theta = np.arccos(cos_theta)
print(theta)

0.643501108793


In [23]:
## comparing the runtime of two maethods of 
## of dot products (loop, dot methods)

x = np.arange(100)
y = np.arange(100)
for i in range(10):
    start = time.time()
    for t in range(1,100000):
        dot = 0 
        for xi,yi in zip(x,y):
            dot += xi*yi
    dt1 = time.time()-start

    start = time.time()
    for t in range(1,100000):
        result = a.dot(b)
    dt2 = time.time()-start

    print(dt1/dt2)


38.868444125180176
38.73688825036035
29.511761894318955
37.97762486370592
29.62350785536093
36.25628339647153
44.63069676183654
31.61138038822688
39.72364131938211
33.41539546287344


In [57]:
## generating the matrices
Z = np.zeros((4,5))
print(Z)
O = np.ones((4,5))
print(O)

R = np.random.random((4,5))
print(R)

print(R.mean())
print(R.var())

# Gaussian distribution
R_ = np.random.randn(4,5)
print(R_)
print(R_.mean())
print(R_.var())

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.17872411  0.12805703  0.72044695  0.61259442  0.73605194]
 [ 0.18574034  0.94996805  0.00531721  0.0773106   0.48824391]
 [ 0.22761087  0.17397823  0.00227445  0.32356182  0.49490136]
 [ 0.7519179   0.62023453  0.36067934  0.02084867  0.98529935]]
0.402188054199
0.0956880481883
[[-1.9035409   0.95710438 -1.51074031  0.40394342 -1.45665125]
 [-0.54190422  1.33362511  0.09031479 -0.15236163 -0.58009637]
 [-1.26593447  1.30142052  0.60828776 -0.38715255 -0.1916459 ]
 [-2.20310975  0.06289167  0.09617909  0.67205799 -0.90788278]]
-0.278759769571
0.999427045775


In [64]:
q = np.array([1,2,3])
p = np.array([4,5,6])
print(p*q) ## element by element multiplication for vector
print(p.dot(q)) ## vector dot product

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a*b)
print(a.dot(b))
print(np.outer(a,b))

[ 4 10 18]
32
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


In [67]:
## trace of array
print(np.diag(a).sum())
print(np.trace(a))

5
5


In [72]:
X = np.random.randn(100,3)
cov = np.cov(X.T)            # cov matrix is symmetric matrix
print(cov)
print(np.linalg.eig(cov))
print(np.linalg.eigh(cov))

[[ 0.95345975  0.19634665 -0.0051474 ]
 [ 0.19634665  1.22666597  0.16068085]
 [-0.0051474   0.16068085  1.19703137]]
(array([ 1.42120783,  0.83173472,  1.12421453]), array([[-0.31880401, -0.82886776, -0.45971973],
       [-0.77382155,  0.5076956 , -0.37874185],
       [-0.5473246 , -0.23499661,  0.80325113]]))
(array([ 0.83173472,  1.12421453,  1.42120783]), array([[ 0.82886776,  0.45971973,  0.31880401],
       [-0.5076956 ,  0.37874185,  0.77382155],
       [ 0.23499661, -0.80325113,  0.5473246 ]]))


In [77]:
A = np.array([[1,2],[3,4]])
b = np.array([1,2])
x = np.linalg.inv(A).dot(b)    # solving eq using inverse of matrix
print(x)
print(np.linalg.solve(A,b))    # solving using solve methods

[  2.22044605e-16   5.00000000e-01]
[ 0.   0.5]
